# Phase 3 — Excel File Handling with Pandas

## Introduction

In this phase, we will learn how to professionally work with Excel files using Python and Pandas. Excel is one of the most widely used tools in businesses, freelancing projects, reporting systems, and data analysis workflows.

A large portion of real-world data analyst and freelancer tasks involve:
- reading Excel files
- cleaning messy spreadsheets
- combining multiple sheets
- generating automated reports
- exporting processed data back to Excel

This phase focuses on practical and industry-relevant Excel operations that are commonly required in:
- office automation
- reporting systems
- business analytics
- data cleaning tasks
- portfolio projects

---

# Objectives of This Phase

By the end of this phase, you will be able to:

- read and write Excel files professionally
- work with multiple sheets
- clean dirty Excel datasets
- automate reporting workflows
- generate Excel-based analysis reports
- handle real-world business spreadsheets
- build practical Excel automation projects

---

# Topics Covered in This Phase

## 1. Reading Excel Files

We will learn how to:
- read Excel files using Pandas
- work with specific sheets
- read multiple sheets
- select required columns
- handle data types
- parse dates properly
- inspect Excel data professionally

This section builds the foundation for all Excel-related workflows.

---

## 2. Writing Excel Files Using Pandas

We will learn how to:
- export DataFrames to Excel
- remove unnecessary indexes
- create custom sheet names
- export selected columns
- generate clean Excel outputs for clients

This is an extremely important skill because clients often require:
- automated reports
- processed Excel exports
- cleaned datasets
- business summaries

---

## 3. Working with Multiple Sheets

Many real-world Excel files contain multiple sheets such as:
- monthly reports
- department-wise data
- regional sales reports
- employee records

We will learn:
- reading specific sheets
- reading all sheets
- writing multiple sheets
- managing workbook structures

This is highly important for practical analyst work and client projects.

---

## 4. Handling Dirty Excel Data

Real-world Excel files are often messy and inconsistent.

We will learn how to handle:
- missing values
- duplicate records
- extra spaces
- inconsistent column names
- formatting issues
- broken or messy datasets

Data cleaning is one of the most valuable skills for:
- freelancers
- data analysts
- automation specialists

---

## 5. Practical Excel Projects

We will build practical mini-projects such as:
- sales report generator
- employee analysis report
- Excel data cleaner
- automated multi-sheet report creator

These projects will help you:
- build a portfolio
- practice real-world workflows
- strengthen your Pandas skills

---

# Why This Phase Is Important

Excel automation is one of the fastest ways to become freelance-ready because many businesses still rely heavily on Excel for:
- reporting
- tracking
- accounting
- inventory management
- HR management
- sales analysis

Learning Excel handling with Python allows you to:
- automate repetitive work
- process large datasets quickly
- create professional reports
- save time for clients
- increase your freelancing value

---

# Tools and Libraries Used

In this phase, we will mainly use:
- Python
- Pandas
- OpenPyXL

Google Colab will be used as the primary environment.

---

# End Goal of This Phase

After completing this phase, you should be comfortable with:
- professional Excel workflows
- Excel automation using Python
- practical business data handling
- preparing Excel-based portfolio projects
- performing real-world analyst tasks

This phase forms an important bridge between:
- Python programming
- data analysis

# 1. Excel Fundamentals

## What Excel Files Are

Excel files are structured data files used to store information in a tabular format. They are widely used in business environments for organizing, analyzing, and reporting data.

Excel files can contain:
- structured tables
- calculations
- multiple sheets
- formatted reports

They are one of the most common formats for business data exchange.

---

## `.xlsx` vs `.csv`

Excel data is commonly stored in two formats.

### `.xlsx` (Excel Workbook)
- Modern Excel format
- Supports multiple sheets
- Supports formatting (colors, fonts, charts)
- Supports formulas and calculations

### `.csv` (Comma-Separated Values)
- Plain text format
- Stores data in simple rows and columns
- No formatting or formulas
- Faster to process in data analysis

### Key Difference Table

| Feature | `.xlsx` | `.csv` |
|---|---|---|
| Sheets | Multiple | Single |
| Formatting | Yes | No |
| Formulas | Yes | No |
| File Type | Binary | Plain text |

---

## Worksheets and Workbooks

### Workbook
A workbook is the complete Excel file.

It can contain:
- one or more sheets
- full dataset collection

Example:
- `sales_data.xlsx`

---

### Worksheet
A worksheet is a single sheet inside a workbook.

Example:
- January sheet
- February sheet
- March sheet

Each worksheet contains tabular data.

---

### Structure View

| Level | Description |
|---|---|
| Workbook | Entire Excel file |
| Worksheet | Single sheet inside file |

---

## Rows, Columns, and Cells

Excel data is arranged in a grid structure.

### Columns
- Vertical structure
- Labeled as A, B, C, etc.
- Represent features/variables

### Rows
- Horizontal structure
- Numbered as 1, 2, 3, etc.
- Represent records/observations

### Cells
- Intersection of row and column
- Example: A1, B3, C5
- Holds a single value

---

### Example Table Structure

| A (Name) | B (Age) | C (Salary) |
|---|---|---|
| Ali | 25 | 50000 |
| Sara | 28 | 70000 |

---

## Why Excel is Heavily Used in Business

Excel is widely used because it is simple, flexible, and powerful for non-programmers.

### Main Reasons

- Easy to learn and use
- Works well for structured data
- Supports calculations and formulas
- Suitable for reporting and dashboards
- Accepted in almost all industries

### Common Business Uses

- Sales reports
- Employee records
- Financial statements
- Inventory tracking
- Budget planning

---

## Professional Insight (Important)

In real freelancing and data analysis work:
- Most raw data comes in Excel format
- Clients expect cleaned and structured Excel reports
- Automation of Excel tasks saves significant time

---

# 2. Reading Excel Files Using Pandas

In this topic, we will learn how to professionally read Excel workbooks using Pandas. First we have to create a real multi-sheet workbook (`company_data.xlsx`), we will use it like a real data analyst or freelancer.

This is one of the most important skills in data analysis because almost every real project starts with reading data correctly.

We will focus on:
- loading Excel files into Pandas
- working with multiple sheets
- selecting specific data
- handling missing values during import
- controlling how data is read

---

In [ ]:
import pandas as pd

employees = pd.DataFrame({
    "Employee_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha", "Usman", "Hina"],
    "Department": ["IT", "HR", "Finance", "IT", "Marketing", "HR"],
    "Age": [28, 32, None, 26, 29, 35],
    "Salary": [70000, 65000, 80000, 60000, None, 72000],
    "Experience_Years": [5, 7, 8, 3, 4, 10]
})

In [ ]:
performance = pd.DataFrame({
    "Employee_ID": [101, 102, 103, 104, 105, 106],
    "Performance_Score": [8, 9, 7, None, 6, 10],
    "Projects_Completed": [12, 15, 10, 8, 9, 20],
    "Overtime_Hours": [5, 2, 7, 3, None, 1]
})

In [ ]:
departments = pd.DataFrame({
    "Department": ["IT", "HR", "Finance", "Marketing"],
    "Head": ["Bilal", "Hina", "Zara", "Fahad"],
    "Budget": [500000, 300000, 400000, 350000],
    "Employees_Count": [2, 2, 1, 1]
})

In [ ]:
employees, performance, departments

(   Employee_ID    Name Department   Age   Salary  Experience_Years
 0          101     Ali         IT  28.0  70000.0                 5
 1          102    Sara         HR  32.0  65000.0                 7
 2          103   Ahmed    Finance   NaN  80000.0                 8
 3          104  Ayesha         IT  26.0  60000.0                 3
 4          105   Usman  Marketing  29.0      NaN                 4
 5          106    Hina         HR  35.0  72000.0                10,
    Employee_ID  Performance_Score  Projects_Completed  Overtime_Hours
 0          101                8.0                  12             5.0
 1          102                9.0                  15             2.0
 2          103                7.0                  10             7.0
 3          104                NaN                   8             3.0
 4          105                6.0                   9             NaN
 5          106               10.0                  20             1.0,
   Department   Head  Budget  Employees_Count
 0         IT  Bilal  500000                2
 1         HR   Hina  300000                2
 2    Finance   Zara  400000                1
 3  Marketing  Fahad  350000                1)

In [ ]:
with pd.ExcelWriter("company_data.xlsx") as writer:
    employees.to_excel(writer, sheet_name="Employees", index=False)
    performance.to_excel(writer, sheet_name="Performance", index=False)
    departments.to_excel(writer, sheet_name="Departments", index=False)

# 1. Reading an Excel File (Basic)

The simplest way to load an Excel file is using:

## `pd.read_excel()`

By default:
- Pandas reads the FIRST sheet only
- loads everything into a DataFrame

---

In [ ]:
df = pd.read_excel('company_data.xlsx')
df

   Employee_ID    Name Department   Age   Salary  Experience_Years
0          101     Ali         IT  28.0  70000.0                 5
1          102    Sara         HR  32.0  65000.0                 7
2          103   Ahmed    Finance   NaN  80000.0                 8
3          104  Ayesha         IT  26.0  60000.0                 3
4          105   Usman  Marketing  29.0      NaN                 4
5          106    Hina         HR  35.0  72000.0                10

# Understanding What Happens Here

When you run `pd.read_excel()`:

- The Excel file is converted into a DataFrame
- Only the first sheet is loaded automatically
- Column headers are taken from the first row
- Missing values are converted to NaN automatically

---

# Important Insight

If your file has multiple sheets (like ours):
- Employees
- Performance
- Departments

Pandas will NOT load all of them by default

# 2. Reading a Specific Sheet

Excel workbooks often contain multiple sheets.

In our case:
- Employees
- Performance
- Departments

You can choose a sheet using `sheet_name`.

---

## Why This Is Important

In real projects:
- HR data is in one sheet
- Sales data in another
- Financial data in another

So selecting correct sheet is critical.

In [ ]:
df = pd.read_excel('company_data.xlsx', sheet_name='Employees')
df

   Employee_ID    Name Department   Age   Salary  Experience_Years
0          101     Ali         IT  28.0  70000.0                 5
1          102    Sara         HR  32.0  65000.0                 7
2          103   Ahmed    Finance   NaN  80000.0                 8
3          104  Ayesha         IT  26.0  60000.0                 3
4          105   Usman  Marketing  29.0      NaN                 4
5          106    Hina         HR  35.0  72000.0                10

# Alternative: Using Sheet Index

Instead of name, you can use index:

| Sheet | Index |
|---|---|
| Employees | 0 |
| Performance | 1 |
| Departments | 2 |

---

## Why index is useful

- Faster when sheet names are unknown
- Useful for automation scripts

In [ ]:
df = pd.read_excel('company_data.xlsx', sheet_name= 2)
df

  Department   Head  Budget  Employees_Count
0         IT  Bilal  500000                2
1         HR   Hina  300000                2
2    Finance   Zara  400000                1
3  Marketing  Fahad  350000                1

# 3. Viewing All Sheet Names

Before working with a file, professionals first check sheet names.

This helps you:
- understand file structure
- avoid mistakes
- choose correct data source

---

## Method: ExcelFile object

In [ ]:
excel_file = pd.ExcelFile('company_data.xlsx')
excel_file.sheet_names

['Employees', 'Performance', 'Departments']

# 4. Selecting Specific Columns (usecols)

Real datasets are large, but you often only need specific columns.

---

## Why this is important

- reduces memory usage
- speeds up processing
- avoids unnecessary data
- very common in freelancing tasks

In [ ]:
df = pd.read_excel('company_data.xlsx', usecols= ['Head', 'Budget'], sheet_name = 2)
df

    Head  Budget
0  Bilal  500000
1   Hina  300000
2   Zara  400000
3  Fahad  350000

# 5. Handling Headers

By default:
- first row is treated as header

But real files may have:
- extra titles
- merged rows
- metadata at top

So you may need to control header position.

In [ ]:
df_header = pd.read_excel('company_data.xlsx', header= 0, sheet_name= 'Employees')
df_header

   Employee_ID    Name Department   Age   Salary  Experience_Years
0          101     Ali         IT  28.0  70000.0                 5
1          102    Sara         HR  32.0  65000.0                 7
2          103   Ahmed    Finance   NaN  80000.0                 8
3          104  Ayesha         IT  26.0  60000.0                 3
4          105   Usman  Marketing  29.0      NaN                 4
5          106    Hina         HR  35.0  72000.0                10

# 6. Skipping Rows (skiprows)

Sometimes Excel files contain:
- titles
- empty rows
- notes
- company logos data rows

So we skip unnecessary rows.

In [ ]:
df_skip = pd.read_excel(
    "company_data.xlsx",
    sheet_name="Employees",
    skiprows = 2,
    header = 0
)

df_skip

   102    Sara         HR    32    65000   7
0  103   Ahmed    Finance   NaN  80000.0   8
1  104  Ayesha         IT  26.0  60000.0   3
2  105   Usman  Marketing  29.0      NaN   4
3  106    Hina         HR  35.0  72000.0  10

# 7. Handling Missing Values During Reading

In real datasets, missing values are very common.

Pandas automatically converts:
- empty cells → NaN

But sometimes data contains:
- "NA"
- "Missing"
- "--"

We must define them manually.

In [ ]:
df_missing = pd.read_excel(
    "company_data.xlsx",
    sheet_name="Employees",
    na_values=["NA", "Missing", "--"]
)

df_missing

   Employee_ID    Name Department   Age   Salary  Experience_Years
0          101     Ali         IT  28.0  70000.0                 5
1          102    Sara         HR  32.0  65000.0                 7
2          103   Ahmed    Finance   NaN  80000.0                 8
3          104  Ayesha         IT  26.0  60000.0                 3
4          105   Usman  Marketing  29.0      NaN                 4
5          106    Hina         HR  35.0  72000.0                10

# 8. Reading All Sheets at Once

Sometimes you need complete workbook data.

Instead of reading one sheet at a time, you can load all sheets.

---

## Output Type

This returns a dictionary:
- key = sheet name
- value = DataFrame

In [ ]:
all_sheets = pd.read_excel('company_data.xlsx', sheet_name= None)
all_sheets

{'Employees':    Employee_ID    Name Department   Age   Salary  Experience_Years
 0          101     Ali         IT  28.0  70000.0                 5
 1          102    Sara         HR  32.0  65000.0                 7
 2          103   Ahmed    Finance   NaN  80000.0                 8
 3          104  Ayesha         IT  26.0  60000.0                 3
 4          105   Usman  Marketing  29.0      NaN                 4
 5          106    Hina         HR  35.0  72000.0                10,
 'Performance':    Employee_ID  Performance_Score  Projects_Completed  Overtime_Hours
 0          101                8.0                  12             5.0
 1          102                9.0                  15             2.0
 2          103                7.0                  10             7.0
 3          104                NaN                   8             3.0
 4          105                6.0                   9             NaN
 5          106               10.0                  20             1.0,
 'Departments':   Department   Head  Budget  Employees_Count
 0         IT  Bilal  500000                2
 1         HR   Hina  300000                2
 2    Finance   Zara  400000                1
 3  Marketing  Fahad  350000                1}

# How to Access Individual Sheets from Dictionary

After loading all sheets:

You can access them like this:

- Employees
- Performance
- Departments

This is very useful in automation tasks.

In [ ]:
all_sheets['Employees']

   Employee_ID    Name Department   Age   Salary  Experience_Years
0          101     Ali         IT  28.0  70000.0                 5
1          102    Sara         HR  32.0  65000.0                 7
2          103   Ahmed    Finance   NaN  80000.0                 8
3          104  Ayesha         IT  26.0  60000.0                 3
4          105   Usman  Marketing  29.0      NaN                 4
5          106    Hina         HR  35.0  72000.0                10

In [ ]:
all_sheets['Performance']

   Employee_ID  Performance_Score  Projects_Completed  Overtime_Hours
0          101                8.0                  12             5.0
1          102                9.0                  15             2.0
2          103                7.0                  10             7.0
3          104                NaN                   8             3.0
4          105                6.0                   9             NaN
5          106               10.0                  20             1.0

# Summary of Topic 2

In this topic, you learned:

## Core Skills
- reading Excel files using Pandas
- working with multi-sheet workbooks
- selecting specific sheets
- accessing sheet names

## Data Control Techniques
- selecting columns using `usecols`
- skipping unnecessary rows
- handling missing values
- reading all sheets at once

---

# Professional Insight

These are real-world skills used in:
- data analysis jobs
- reporting automation
- business dashboards

Mastering this ensures you can handle any Excel file from clients confidently.

# 3. Writing Excel Files Using Pandas

In real-world data analysis, reading data is only half of the work.

The other very important skill is:
- exporting processed data back to Excel

This is where you:
- deliver results to clients
- generate reports
- automate business workflows
- create clean datasets from raw data

Pandas provides a powerful function:

## `df.to_excel()`

This function allows you to export a DataFrame into an Excel file.

---

# 1. Basic Export to Excel

The simplest way to save data is:

``df.to_excel("output.xlsx")``


This will:
- create an Excel file
- store DataFrame inside it
- include row indexes by default

---

# Why This Is Important

In freelancing, clients often expect:
- cleaned Excel files
- structured reports
- processed datasets

So exporting data is a core skill.

In [ ]:
df = pd.read_excel('company_data.xlsx', sheet_name = 'Employees')
df.to_excel('employees_output.xlsx')

# 2. Removing Index Column (VERY IMPORTANT)

By default Pandas adds an extra column:

- index (0, 1, 2, ...)

But in professional Excel reports:
- this is usually NOT needed

So we remove it using:

## `index=False`

---

# Why remove index?

Because:
- clients don’t need it
- makes report cleaner
- improves presentation quality

In [ ]:
df.to_excel("employees_clean.xlsx", index=False)

# 3. Writing Specific Columns Only

Sometimes you don’t want to export full dataset.

Example:
- only Name, Salary, Department

This is very common in freelancing tasks.

---

## Why this is useful

- reduces file size
- hides unnecessary data
- creates focused reports

In [ ]:
df_Selected = df[["Employee_ID", "Name", "Salary", "Department"]]
df_Selected.to_excel('employees_selected.xlsx', index= False)

# 4. Naming Excel Sheets (VERY IMPORTANT)

Excel files can contain multiple sheets.

You can define sheet names using:

## `sheet_name`

---

# Why this matters

In real projects:
- HR data → one sheet
- Finance data → another sheet
- Performance data → another sheet

Proper naming makes files professional and readable.

In [ ]:
with pd.ExcelWriter('company_data.xlsx') as writer:
  df.to_excel(writer, sheet_name = 'Employees', index=False)

# 5. Writing Multiple Sheets (Professional Skill)

This is extremely important for:
- business reporting
- dashboards
- automation systems

You can write multiple DataFrames into one Excel file.

In [ ]:
employees = pd.read_excel("company_data.xlsx", sheet_name="Employees")
performance = pd.read_excel("company_data.xlsx", sheet_name="Performance")
departments = pd.read_excel("company_data.xlsx", sheet_name="Departments")

with pd.ExcelWriter("full_company_report.xlsx") as writer:
    employees.to_excel(writer, sheet_name="Employees", index=False)
    performance.to_excel(writer, sheet_name="Performance", index=False)
    departments.to_excel(writer, sheet_name="Departments", index=False)

# 6. Professional Export Workflow (Real Industry Use)

In real jobs, workflow looks like:

## Step 1
Read raw Excel file

## Step 2
Clean data (missing values, duplicates, formatting)

## Step 3
Analyze data

## Step 4
Export final report

---

# Example Use Case

- Client gives messy employee file
- You clean it in Python
- You export final Excel report

In [ ]:
clean_df = df.dropna()

clean_df.to_excel("clean_employees.xlsx", index=False)

# 7. Common Mistakes in Writing Excel Files

## Mistake 1: Forgetting index=False
- leads to unnecessary column in output

## Mistake 2: Overwriting important files
- always use new filenames

## Mistake 3: Not using ExcelWriter for multiple sheets
- causes file overwrite issues

---

# Summary

In this topic, you learned:

## Core Skills
- exporting DataFrames to Excel
- removing index column
- selecting specific columns
- writing multiple sheets

## Professional Skills
- generating reports
- creating clean client deliverables
- automating Excel workflows

---


Mastering this makes you capable of handling real client work confidently.

# 5. Handling Dirty Excel Data

Real-world Excel files are rarely clean.

Most business datasets contain:
- missing values
- duplicate records
- inconsistent formatting
- extra spaces
- incorrect column names

Cleaning dirty data is one of the MOST important skills for:
- data analysts
- freelancers
- ML engineers
- automation specialists

A large portion of real analyst work is actually:
- cleaning
- fixing
- standardizing data

before analysis even starts.

---

# What Is Dirty Data?

Dirty data means:
- incomplete data
- inconsistent data
- incorrectly formatted data
- duplicate data

Dirty datasets produce:
- wrong analysis
- incorrect reports
- poor machine learning results

So cleaning data is a critical professional skill.

# 1. Handling Missing Values

Missing values are one of the most common problems in datasets.

Examples:
- empty salary
- missing age
- missing department
- incomplete dates

Pandas represents missing values as:

## `NaN`

---

# Why Missing Values Matter

Missing values can:
- break calculations
- reduce model accuracy
- create wrong summaries
- cause analysis errors

In [ ]:
import pandas as pd

df = pd.read_excel("company_data.xlsx", sheet_name="Employees")

df

   Employee_ID    Name Department   Age   Salary  Experience_Years
0          101     Ali         IT  28.0  70000.0                 5
1          102    Sara         HR  32.0  65000.0                 7
2          103   Ahmed    Finance   NaN  80000.0                 8
3          104  Ayesha         IT  26.0  60000.0                 3
4          105   Usman  Marketing  29.0      NaN                 4
5          106    Hina         HR  35.0  72000.0                10

# Detecting Missing Values

Use:

## `isnull()`

to identify missing data.

In [ ]:
df.isnull()

   Employee_ID   Name  Department    Age  Salary  Experience_Years
0        False  False       False  False   False             False
1        False  False       False  False   False             False
2        False  False       False   True   False             False
3        False  False       False  False   False             False
4        False  False       False  False    True             False
5        False  False       False  False   False             False

# Counting Missing Values

To see total missing values in each column:

In [ ]:
df.isnull().sum()

Employee_ID         0
Name                0
Department          0
Age                 1
Salary              1
Experience_Years    0
dtype: int64

# Removing Missing Values

Use:

## `dropna()`

This removes rows containing missing values.

---

# Important Note

This is useful when:
- missing data is small
- incomplete rows are not important

But excessive removal can lose valuable data.

In [ ]:
df_clean = df.dropna()

df_clean

   Employee_ID    Name Department   Age   Salary  Experience_Years
0          101     Ali         IT  28.0  70000.0                 5
1          102    Sara         HR  32.0  65000.0                 7
3          104  Ayesha         IT  26.0  60000.0                 3
5          106    Hina         HR  35.0  72000.0                10

# Filling Missing Values

Instead of removing rows, we often fill missing data.

This is more professional in many cases.

Use:

## `fillna()`

In [ ]:
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

df

   Employee_ID    Name Department   Age   Salary  Experience_Years
0          101     Ali         IT  28.0  70000.0                 5
1          102    Sara         HR  32.0  65000.0                 7
2          103   Ahmed    Finance   NaN  80000.0                 8
3          104  Ayesha         IT  26.0  60000.0                 3
4          105   Usman  Marketing  29.0  69400.0                 4
5          106    Hina         HR  35.0  72000.0                10

# Professional Insight

Common filling strategies:

| Column Type | Common Fill Method |
|---|---|
| Numeric | mean / median |
| Text | mode / Unknown |
| Dates | previous date or estimated |

---

# Example

- missing salary → average salary
- missing department → "Unknown"

# 2. Handling Duplicate Rows

Duplicate data is another common real-world issue.

Duplicates happen because:
- repeated entries
- system errors
- manual mistakes
- merged files

---

# Why Duplicates Are Dangerous

Duplicates can:
- inflate reports
- distort averages
- create wrong statistics
- affect ML models

In [ ]:
df_duplicates = pd.concat([df, df])

df_duplicates

   Employee_ID    Name Department   Age   Salary  Experience_Years
0          101     Ali         IT  28.0  70000.0                 5
1          102    Sara         HR  32.0  65000.0                 7
2          103   Ahmed    Finance   NaN  80000.0                 8
3          104  Ayesha         IT  26.0  60000.0                 3
4          105   Usman  Marketing  29.0  69400.0                 4
5          106    Hina         HR  35.0  72000.0                10
0          101     Ali         IT  28.0  70000.0                 5
1          102    Sara         HR  32.0  65000.0                 7
2          103   Ahmed    Finance   NaN  80000.0                 8
3          104  Ayesha         IT  26.0  60000.0                 3
4          105   Usman  Marketing  29.0  69400.0                 4
5          106    Hina         HR  35.0  72000.0                10

# Detecting Duplicate Rows

Use:

## `duplicated()`

In [ ]:
df_duplicates.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
0     True
1     True
2     True
3     True
4     True
5     True
dtype: bool

# Removing Duplicate Rows

Use:

## `drop_duplicates()`

In [ ]:
df_no_duplicates = df_duplicates.drop_duplicates()

df_no_duplicates

   Employee_ID    Name Department   Age   Salary  Experience_Years
0          101     Ali         IT  28.0  70000.0                 5
1          102    Sara         HR  32.0  65000.0                 7
2          103   Ahmed    Finance   NaN  80000.0                 8
3          104  Ayesha         IT  26.0  60000.0                 3
4          105   Usman  Marketing  29.0  69400.0                 4
5          106    Hina         HR  35.0  72000.0                10

# 3. Handling Extra Spaces

Extra spaces are extremely common in Excel files.

Example:
- `" IT"`
- `"HR "`
- `" Finance "`

These spaces create analysis problems because:
- `"IT"` and `" IT"` are treated differently

This causes:
- grouping issues
- filtering problems
- incorrect counts

In [ ]:
df["Department"] = df["Department"].str.strip()

df

   Employee_ID    Name Department   Age   Salary  Experience_Years
0          101     Ali         IT  28.0  70000.0                 5
1          102    Sara         HR  32.0  65000.0                 7
2          103   Ahmed    Finance   NaN  80000.0                 8
3          104  Ayesha         IT  26.0  60000.0                 3
4          105   Usman  Marketing  29.0  69400.0                 4
5          106    Hina         HR  35.0  72000.0                10

# Understanding `str.strip()`

`strip()` removes:
- leading spaces
- trailing spaces

Example:

| Before | After |
|---|---|
| `" IT"` | `"IT"` |
| `"HR "` | `"HR"` |

---

# Professional Insight

Always clean text columns before:
- grouping
- filtering
- merging datasets

# 4. Handling Inconsistent Column Names

Real datasets often contain bad column names like:

- `" Employee Name "`
- `"salary"`
- `"Joining Date"`
- `"DEPARTMENT"`

Inconsistent columns create coding confusion.

Professionals standardize column names immediately.

In [ ]:
df.columns

Index(['Employee_ID', 'Name', 'Department', 'Age', 'Salary',
       'Experience_Years'],
      dtype='object')

# Standardizing Column Names

A professional workflow is:
- lowercase names
- remove spaces
- replace spaces with underscores

In [ ]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

df.columns

Index(['employee_id', 'name', 'department', 'age', 'salary',
       'experience_years'],
      dtype='object')

# Result Example

| Before | After |
|---|---|
| Employee ID | employee_id |
| Joining Date | joining_date |

---

# Why This Matters

Consistent columns:
- improve readability
- reduce errors
- make automation easier
- improve team collaboration

# 5. Handling Broken Formatting Issues

Real Excel files may contain:
- mixed data types
- wrong date formats
- numbers stored as text
- inconsistent capitalization

Example:
- `"it"`
- `"IT"`
- `"It"`

All represent same department but are treated differently.

In [ ]:
df["department"] = df["department"].str.upper()

df

   employee_id    name department   age   salary  experience_years
0          101     Ali         IT  28.0  70000.0                 5
1          102    Sara         HR  32.0  65000.0                 7
2          103   Ahmed    FINANCE   NaN  80000.0                 8
3          104  Ayesha         IT  26.0  60000.0                 3
4          105   Usman  MARKETING  29.0  69400.0                 4
5          106    Hina         HR  35.0  72000.0                10

# Why Standardization Is Important

Consistent formatting ensures:
- correct grouping
- correct filtering
- accurate reports
- reliable ML preprocessing

---

# Common Standardization Methods

| Method | Purpose |
|---|---|
| `str.upper()` | Convert to uppercase |
| `str.lower()` | Convert to lowercase |
| `str.title()` | Capitalize words |

# Professional Cleaning Workflow

Professional analysts usually follow this order:

## Step 1
Load dataset

## Step 2
Inspect missing values

## Step 3
Remove duplicates

## Step 4
Clean text columns

## Step 5
Standardize column names

## Step 6
Fix formatting issues

## Step 7
Start analysis

---

# This workflow is extremely important in:
- freelancing
- business analytics
- machine learning
- reporting automation

# Summary

In this topic, you learned how to handle:

- missing values
- duplicate rows
- extra spaces
- inconsistent column names
- broken formatting issues

---

# Most Important Professional Insight

A data analyst who cannot clean dirty data:
- cannot perform reliable analysis
- cannot build reliable ML models
- cannot handle real client projects properly

Data cleaning is one of the most valuable real-world skills in data analysis.