# PHASE 4 — JSON File Handling

## Overview

In this phase, we will learn how to professionally work with JSON files using Python. JSON is one of the most important and widely used data formats in:
- APIs
- web applications
- automation systems
- web scraping
- machine learning pipelines

Modern applications and services exchange data mostly in JSON format, so understanding JSON handling is an essential practical skill for:
- data analysts
- automation developers
- ML engineers

This phase focuses on practical JSON handling workflows commonly used in real-world projects.

---

# Topics Covered in This Phase

## 1. JSON Basics

We will learn:
- what JSON is
- JSON structure
- reading JSON files
- writing JSON files
- converting Python objects into JSON

We will master:
- `json.load()`
- `json.dump()`

These are the foundation of JSON handling in Python.

---

## 2. Nested JSON (Very Important)

Real-world JSON data is usually nested and hierarchical.

We will learn how to access deeply nested structures such as:

```python
data["user"]["address"]
```

This is one of the most important skills for:
- API responses
- scraped web data
- cloud services
- automation systems

---

## 3. Converting JSON to Python Objects

We will learn how JSON data maps into Python structures like:
- dictionaries
- lists
- nested dictionaries

This topic is extremely important because almost all JSON processing depends on understanding Python object structures properly.

---

## 4. Working with JSON and Pandas

We will learn:
- converting JSON into DataFrames
- loading JSON data into Pandas
- analyzing structured JSON datasets

This is highly important for:
- data analysis
- APIs
- machine learning preprocessing

---


# Why This Phase Is Important

As a freelancer or data analyst, you will frequently:
- fetch API data
- process JSON responses
- work with nested data
- clean structured datasets
- prepare JSON data for analysis

Many modern technologies heavily rely on JSON, including:
- REST APIs
- cloud platforms
- web scraping tools
- machine learning pipelines

JSON handling is one of the core modern data skills.

---

# End Goal of This Phase

By the end of this phase, you will be able to:
- read and write JSON files confidently
- understand nested JSON structures
- process API responses
- convert JSON into Pandas DataFrames
- handle real-world JSON datasets professionally

This phase forms an important bridge between:
- Python programming
- APIs
- automation
- web scraping
- data analysis
- machine learning workflows

# 1. JSON Basics

JSON is one of the most important data formats in modern programming and data analysis. Before working with APIs, web scraping, automation, or machine learning pipelines, you must understand JSON properly.

In this topic, we will learn:
- what JSON is
- JSON structure
- reading JSON files
- writing JSON files
- converting Python objects into JSON

We will mainly use:
- `json.load()`
- `json.dump()`

These are the foundation of JSON handling in Python.

---

# 1. What Is JSON?

JSON stands for:

```plaintext
JavaScript Object Notation
```

JSON is a lightweight format used to store and exchange data.

It is widely used because:
- easy for humans to read
- easy for machines to process
- supported by almost every programming language

---

# Real-World Usage of JSON

JSON is heavily used in:
- APIs
- web applications
- cloud services
- automation systems
- configuration files
- machine learning pipelines

---

# Example of JSON Data

```json
{
    "name": "Ali",
    "age": 25,
    "department": "IT"
}
```

This stores structured information using:
- key-value pairs

---

# Understanding JSON Structure

JSON mainly contains:
- objects
- arrays
- key-value pairs

---

# JSON Object

A JSON object is enclosed in:

```plaintext
{}
```

Example:

```json
{
    "name": "Sara",
    "salary": 70000
}
```

---

# JSON Array

A JSON array is enclosed in:

```plaintext
[]
```

Example:

```json
[
    "Python",
    "SQL",
    "Pandas"
]
```

---

# Key-Value Pairs

JSON stores data as:

```plaintext
"key": value
```

Example:

```json
{
    "city": "Lahore"
}
```

Here:
- `"city"` → key
- `"Lahore"` → value

---

# Important JSON Rules

| Rule | Example |
|---|---|
| Keys use double quotes | `"name"` |
| Strings use double quotes | `"Ali"` |
| Objects use `{}` | `{ "age": 25 }` |
| Arrays use `[]` | `[1, 2, 3]` |
| Data separated by commas | `"a":1, "b":2` |

---

# JSON vs Python Dictionary

JSON looks very similar to Python dictionaries.

Example Python dictionary:

```python
{
    "name": "Ali",
    "age": 25
}
```

Main difference:

| JSON | Python |
|---|---|
| Double quotes required | Single or double allowed |
| Stored as file/string | Native Python object |
| Used for data exchange | Used inside Python |

---

# 2. Importing JSON Module

Python provides a built-in module:

```python
json
```

This module allows us to:
- read JSON files
- write JSON files
- convert Python objects to JSON
- convert JSON to Python objects

In [ ]:
import json

# 3. Writing JSON Files (`json.dump()`)

One of the most important operations is saving Python data into a JSON file.

We use:

## `json.dump()`

---

# Syntax

```python
json.dump(python_object, file_object)
```

---

# What Happens Here?

- Python dictionary → converted into JSON
- Data gets stored inside a `.json` file

---

# Example Workflow

```plaintext
Python Dictionary
        ↓
json.dump()
        ↓
JSON File
```

In [ ]:
employee = {
    "name": "Ali",
    "age": 25,
    "department": "IT",
    "salary": 70000
}

with open('employees.json', 'w') as file:
  json.dump(employee, file)

# Understanding the Code

| Part | Purpose |
|---|---|
| `"employee.json"` | JSON filename |
| `"w"` | Write mode |
| `json.dump()` | Save dictionary as JSON |

---

# Output File Content

The generated JSON file will contain:

```json
{
    "name": "Ali",
    "age": 25,
    "department": "IT",
    "salary": 70000
}
```

---

# Professional Insight

JSON files are commonly used for:
- API responses
- configuration files
- storing structured data
- automation workflows

Learning `json.dump()` is essential for real-world projects.

markdown
# 4. Making JSON More Readable (`indent`)

By default, JSON may appear compressed into one line.

Professionals use:
- indentation
- proper formatting

for readability.

---

# Using `indent`

The `indent` parameter formats JSON neatly.

In [ ]:
import json

employee = {
    "name": "Sara",
    "age": 28,
    "department": "HR"
}

with open("formatted_employee.json", "w") as file:
    json.dump(employee, file, indent=4)

In [ ]:
with open("formatted_employee.json", "r") as file:
    print(file.read())

{
    "name": "Sara",
    "age": 28,
    "department": "HR"
}

# Why `indent` Is Important

Benefits:
- easier to read
- easier to debug
- professional formatting
- better collaboration

---

# Common Professional Practice

Most developers use:

```python
indent=4
```

for clean formatting.

markdown
# 5. Reading JSON Files (`json.load()`)

Now we will read JSON data from files.

We use:

## `json.load()`

---

# Syntax

```python
json.load(file_object)
```

---

# What Happens Here?

- JSON file → converted into Python object

Usually:
- JSON object → Python dictionary
- JSON array → Python list

---

# Workflow

```plaintext
JSON File
      ↓
json.load()
      ↓
Python Dictionary/List
```

In [ ]:
with open('employees.json', 'r') as file:
  data= json.load(file)

print(data)

{'name': 'Ali', 'age': 25, 'department': 'IT', 'salary': 70000}

# Understanding the Code

| Part | Purpose |
|---|---|
| `"r"` | Read mode |
| `json.load()` | Read JSON file |
| `data` | Python dictionary |

---

# Important Concept

After loading:

```python
data
```

is now a normal Python dictionary.

This means you can use:
- indexing
- loops
- conditions
- dictionary methods

In [ ]:
print(data['name'])
print(data['department'])

Ali
IT

# 6. JSON Data Types vs Python Data Types

Understanding conversion is important professionally.

| JSON | Python |
|---|---|
| Object | dict |
| Array | list |
| String | str |
| Number | int / float |
| true | True |
| false | False |
| null | None |

---

# Example

JSON:

```json
{
    "active": true,
    "salary": null
}
```

Python becomes:

```python
{
    "active": True,
    "salary": None
}
```

markdown
# 7. Common Beginner Mistakes

## Mistake 1: Using Single Quotes in JSON

Wrong:

```json
{'name': 'Ali'}
```

Correct:

```json
{"name": "Ali"}
```

---

## Mistake 2: Forgetting to Import `json`

Always import:

```python
import json
```

---

## Mistake 3: Confusing `load` and `dump`

| Function | Purpose |
|---|---|
| `json.load()` | Read JSON |
| `json.dump()` | Write JSON |

---

## Mistake 4: Forgetting File Modes

| Mode | Purpose |
|---|---|
| `"r"` | Read |
| `"w"` | Write |

markdown
# 8. Professional Workflow

A common real-world JSON workflow:

## Step 1
Receive JSON data from API

## Step 2
Read JSON using `json.load()`

## Step 3
Extract required information

## Step 4
Process or analyze data

## Step 5
Save cleaned data using `json.dump()`

This workflow is used heavily in:
- APIs
- automation
- web scraping
- machine learning pipelines

# Summary

In this topic, you learned:

- what JSON is
- JSON structure
- JSON objects and arrays
- key-value pairs
- differences between JSON and Python dictionaries
- writing JSON using `json.dump()`
- reading JSON using `json.load()`
- JSON-to-Python data conversion

These concepts form the foundation for all upcoming JSON and API handling topics.

# 2. Nested JSON (Very Important)

Real-world JSON data is usually NOT flat and simple.

Most APIs and modern applications return:
- nested objects
- lists inside objects
- objects inside lists

This is called:

# Nested JSON

Understanding nested JSON is one of the MOST important real-world data skills because APIs heavily use hierarchical data structures.

---

# Why Nested JSON Is Important

Nested JSON is used in:
- API responses
- web scraping
- cloud services
- automation systems
- machine learning pipelines

As a data analyst or freelancer, you will frequently extract information from deeply nested structures.

---

# 1. Understanding Nested Structure

A nested JSON contains:
- dictionaries inside dictionaries
- lists inside dictionaries
- dictionaries inside lists

---

# Example Nested JSON

```json
{
    "user": {
        "name": "Ali",
        "age": 25,
        "address": {
            "city": "Lahore",
            "country": "Pakistan"
        }
    }
}
```

---

# Structure Visualization

```plaintext
user
 ├── name
 ├── age
 └── address
      ├── city
      └── country
```

---

# Key Concept

To access nested data:

We move level-by-level using keys.

In [ ]:
import json

data = {
    "user": {
        "name": "Ali",
        "age": 25,
        "address": {
            "city": "Lahore",
            "country": "Pakistan"
        }
    }
}

data

{'user': {'name': 'Ali',
  'age': 25,
  'address': {'city': 'Lahore', 'country': 'Pakistan'}}}

# 2. Accessing Nested Data

To access nested values:

```python
data["user"]["address"]
```

Each key moves one level deeper.

---

# Step-by-Step Breakdown

## First Level

```python
data["user"]
```

returns:

```python
{
    "name": "Ali",
    "age": 25,
    "address": {...}
}
```

---

## Second Level

```python
data["user"]["address"]
```

returns:

```python
{
    "city": "Lahore",
    "country": "Pakistan"
}
```

In [ ]:
print(data['user'])
print(data['user']['address'])

{'name': 'Ali', 'age': 25, 'address': {'city': 'Lahore', 'country': 'Pakistan'}}
{'city': 'Lahore', 'country': 'Pakistan'}

# 3. Accessing Specific Nested Values

Now we access actual values.

Example:

```python
data["user"]["address"]["city"]
```

---

# Understanding the Flow

| Level | Key |
|---|---|
| Level 1 | `"user"` |
| Level 2 | `"address"` |
| Level 3 | `"city"` |

Each key takes us deeper into the structure.

In [ ]:
print(data['user']['address']['city'])

Lahore

# 4. Nested JSON with Lists

Real APIs often contain lists inside JSON.

Example:
- multiple users
- multiple products
- multiple posts

This is extremely common in API responses.

In [ ]:
company = {
    "employees": [
        {
            "name": "Ali",
            "department": "IT"
        },
        {
            "name": "Sara",
            "department": "HR"
        }
    ]
}

company

{'employees': [{'name': 'Ali', 'department': 'IT'},
  {'name': 'Sara', 'department': 'HR'}]}

# Understanding This Structure

```plaintext
employees
   ├── employee 1
   │      ├── name
   │      └── department
   │
   └── employee 2
          ├── name
          └── department
```

---

# Important Concept

When data contains a list:

We use:
- indexes (`0`, `1`, `2`)
- then dictionary keys

In [ ]:
company

{'employees': [{'name': 'Ali', 'department': 'IT'},
  {'name': 'Sara', 'department': 'HR'}]}

# 5. Accessing List Items in Nested JSON

To access first employee:

```python
company["employees"][0]
```

To access second employee:

```python
company["employees"][1]
```

---

# Important Rule

| Structure | Access Method |
|---|---|
| Dictionary | keys |
| List | indexes |

You must identify the structure correctly.

In [ ]:
print(company['employees'])

[{'name': 'Ali', 'department': 'IT'}, {'name': 'Sara', 'department': 'HR'}]

In [ ]:
print(company['employees'][1])

{'name': 'Sara', 'department': 'HR'}

# 6. Accessing Specific Values from Nested Lists

Now combine:
- list indexing
- dictionary keys

Example:

```python
company["employees"][0]["name"]
```

---

# Breakdown

| Part | Meaning |
|---|---|
| `"employees"` | access list |
| `[0]` | first employee |
| `"name"` | employee name |

In [ ]:
print(company['employees'][1]['name'])

Sara

In [ ]:
print(company["employees"][1]["department"])

HR

# 7. Real-World API Style Example

Most APIs return complex nested JSON structures.

Example:
- weather APIs
- social media APIs
- e-commerce APIs

You must know how to navigate deeply nested data.

In [ ]:
api_data = {
    "status": "success",
    "data": {
        "user": {
            "name": "Ahmed",
            "email": "ahmed@gmail.com",
            "location": {
                "city": "Karachi",
                "country": "Pakistan"
            }
        }
    }
}

api_data

{'status': 'success',
 'data': {'user': {'name': 'Ahmed',
   'email': 'ahmed@gmail.com',
   'location': {'city': 'Karachi', 'country': 'Pakistan'}}}}

# Accessing Deeply Nested API Data

Example:

```python
api_data["data"]["user"]["location"]["city"]
```

This style is extremely common in APIs.

In [ ]:
print(api_data["data"]["user"]["name"])

Ahmed

In [ ]:
print(api_data["data"]["user"]["location"]["city"])

Karachi

# 8. Common Beginner Mistakes

## Mistake 1: Confusing Lists and Dictionaries

Wrong:

```python
data["employees"]["name"]
```

Correct:

```python
data["employees"][0]["name"]
```

because:
- `employees` is a list

---

## Mistake 2: Forgetting Levels

Wrong:

```python
data["city"]
```

Correct:

```python
data["user"]["address"]["city"]
```

---

## Mistake 3: Not Inspecting Structure First

Professional developers first inspect JSON before extracting values.

In [ ]:
print(api_data)

{'status': 'success', 'data': {'user': {'name': 'Ahmed', 'email': 'ahmed@gmail.com', 'location': {'city': 'Karachi', 'country': 'Pakistan'}}}}

# Professional Insight

Before working with any API or JSON:

## Step 1
Inspect full structure

## Step 2
Identify:
- dictionaries
- lists
- nesting levels

## Step 3
Access data level-by-level

This is the standard professional workflow.

# Summary

In this topic, you learned:

- what nested JSON is
- nested dictionaries
- lists inside JSON
- accessing deeply nested values
- combining keys and indexes
- working with API-style JSON structures

---

# Most Important Concept

Always identify:

| Structure | Access Method |
|---|---|
| Dictionary | keys |
| List | indexes |

Mastering nested JSON is essential for:
- APIs
- automation
- web scraping
- machine learning data pipelines

# 3. Converting JSON to Python Objects

One of the most important concepts in JSON handling is understanding how JSON data becomes normal Python objects after loading.

This topic is extremely important because:
- almost all JSON processing depends on Python structures
- APIs return JSON that becomes Python objects
- data extraction depends on understanding object types

If you do not understand Python object mapping properly, nested JSON becomes very confusing.

---

# Main Goal of This Topic

We will understand how JSON maps into:
- Python dictionaries
- Python lists
- nested dictionaries
- combinations of lists and dictionaries

This is a foundational professional skill for:
- APIs
- automation
- web scraping
- machine learning pipelines

# 1. JSON Object → Python Dictionary

The MOST important mapping:

| JSON | Python |
|---|---|
| Object `{}` | Dictionary `dict` |

---

# Example JSON Object

```json
{
    "name": "Ali",
    "age": 25
}
```

After loading into Python:

```python
{
    "name": "Ali",
    "age": 25
}
```

becomes a Python dictionary.

In [ ]:
json_data = '''
{
    "name": "Ali",
    "age": 25
}
'''

data = json.loads(json_data)

print(data)
print(type(data))

{'name': 'Ali', 'age': 25}
<class 'dict'>

# Understanding the Code

## `json.loads()`

Converts:
- JSON string
→ Python object

---

# Output Type

```python
<class 'dict'>
```

This means:
- the JSON object became a Python dictionary

---

# Important Note

There are two similar functions:

| Function | Purpose |
|---|---|
| `json.load()` | Read JSON file |
| `json.loads()` | Read JSON string |

We use `loads()` when JSON is already inside a Python string.

# 2. Accessing Dictionary Data

Since JSON objects become dictionaries:

We use:
- dictionary keys

to access values.

In [ ]:
print(data["name"])
print(data["age"])

Ali
25

# 3. JSON Array → Python List

Another very important mapping:

| JSON | Python |
|---|---|
| Array `[]` | List `list` |

---

# Example JSON Array

```json
[
    "Python",
    "SQL",
    "Pandas"
]
```

becomes:

```python
["Python", "SQL", "Pandas"]
```

In [ ]:
json_array = '''
[
  "Python",
  "SQL",
  "Pandas"
]
'''

skills = json.loads(json_array)
print(skills)
print(type(skills))

['Python', 'SQL', 'Pandas']
<class 'list'>

# Understanding the Output

```python
<class 'list'>
```

This means:
- JSON array became Python list

---

# Important Concept

After conversion:
- lists behave like normal Python lists
- you can use indexing
- loops
- list methods

In [ ]:
print(skills[0])
print(skills[1])

Python
SQL

# 4. Nested JSON → Nested Python Objects

Real-world JSON usually contains combinations of:
- dictionaries
- lists
- nested dictionaries

After loading:
- JSON becomes nested Python structures

In [ ]:
nested_json = '''
{
    "employee": {
        "name": "Sara",
        "skills": ["Python", "SQL"],
        "address": {
            "city": "Lahore",
            "country": "Pakistan"
        }
    }
}
'''

employee_data = json.loads(nested_json)

print(employee_data)

{'employee': {'name': 'Sara', 'skills': ['Python', 'SQL'], 'address': {'city': 'Lahore', 'country': 'Pakistan'}}}

In [ ]:
print(employee_data['employee']['skills'][0])

Python

# Structure After Conversion

```plaintext
Dictionary
   └── employee
          ├── name → string
          ├── skills → list
          └── address → dictionary
```

---

# Important Professional Skill

You must identify:
- which part is dictionary
- which part is list
- which part is string

before extracting data.

# 5. Understanding Object Types

Professionals often inspect types before processing data.

Use:

```python
type()
```

to inspect structures.

In [ ]:
print(type(employee_data))
print(type(employee_data["employee"]))
print(type(employee_data["employee"]["skills"]))
print(type(employee_data["employee"]["address"]))

<class 'dict'>
<class 'dict'>
<class 'list'>
<class 'dict'>

# Expected Output Types

| Expression | Type |
|---|---|
| `employee_data` | dict |
| `employee_data["employee"]` | dict |
| `employee_data["employee"]["skills"]` | list |
| `employee_data["employee"]["address"]` | dict |

---

# Why This Is Important

Most beginner confusion happens because:
- they don't know object type
- they use keys on lists
- they use indexes on dictionaries

# 6. Accessing Nested Python Objects

Now we use:
- keys for dictionaries
- indexes for lists

In [ ]:
print(employee_data["employee"]["name"])

Sara

In [ ]:
print(employee_data["employee"]["skills"][0])

Python

In [ ]:
print(employee_data["employee"]["address"]["city"])

Lahore

# Breakdown Example

```python
employee_data["employee"]["skills"][0]
```

| Part | Meaning |
|---|---|
| `"employee"` | dictionary key |
| `"skills"` | nested key |
| `[0]` | first list item |

---

# Important Rule

| Structure | Access Method |
|---|---|
| Dictionary | keys |
| List | indexes |

# 7. JSON Boolean and Null Conversion

JSON values also map into Python values.

| JSON | Python |
|---|---|
| `true` | `True` |
| `false` | `False` |
| `null` | `None` |

---

# Example JSON

```json
{
    "active": true,
    "salary": null
}
```

In [ ]:
json_info = '''
{
    "active": true,
    "salary": null
}
'''

info = json.loads(json_info)

print(info)
print(type(info["active"]))
print(type(info["salary"]))

{'active': True, 'salary': None}
<class 'bool'>
<class 'NoneType'>

# Important Insight

After conversion:
- `true` becomes Python boolean
- `null` becomes Python `None`

This is heavily used in:
- APIs
- missing data handling
- automation systems

# 8. Common Beginner Mistakes

## Mistake 1: Confusing JSON and Python Syntax

JSON:

```json
{
    "name": "Ali"
}
```

Python dictionary:

```python
{
    "name": "Ali"
}
```

They look similar but are different concepts.

---

## Mistake 2: Using Indexes on Dictionaries

Wrong:

```python
data[0]
```

Correct:

```python
data["name"]
```

---

## Mistake 3: Using Keys on Lists

Wrong:

```python
skills["Python"]
```

Correct:

```python
skills[0]
```

---

## Mistake 4: Ignoring Object Types

Always inspect structure using:

```python
type()
```

# Professional Workflow

Professional JSON processing usually follows this workflow:

## Step 1
Load JSON

## Step 2
Inspect object types

## Step 3
Identify:
- dictionaries
- lists
- nesting levels

## Step 4
Extract required data

## Step 5
Convert into DataFrame or analysis format

This workflow is heavily used in:
- APIs
- automation
- web scraping
- machine learning preprocessing

# Summary

In this topic, you learned:

- JSON object → Python dictionary
- JSON array → Python list
- nested JSON → nested Python objects
- object type inspection using `type()`
- dictionary key access
- list indexing
- JSON boolean and null conversion

---

# Most Important Concept

Always identify the object type first:

| Structure | Access Method |
|---|---|
| Dictionary | keys |
| List | indexes |

Understanding this properly makes nested JSON and API handling much easier professionally.

# 4. Working with JSON and Pandas

JSON and Pandas are commonly used together in modern data analysis workflows.

In real-world projects:
- APIs return JSON
- web scraping tools produce JSON
- cloud services exchange JSON data

Data analysts usually convert this JSON data into Pandas DataFrames for:
- analysis
- cleaning
- visualization
- machine learning preprocessing

This is one of the most practical and important professional skills.

---

# What We Will Learn

In this topic, we will learn:
- converting JSON into DataFrames
- loading JSON data into Pandas
- analyzing structured JSON datasets

---

# Why This Topic Is Important

This workflow is heavily used in:
- APIs
- automation systems
- data engineering
- machine learning pipelines
- real-world freelancing projects

Most modern data systems exchange information using JSON.

# 1. Importing Required Libraries

We mainly use:
- `json`
- `pandas`

for JSON data analysis workflows.

In [ ]:
import json
import pandas as pd

# 2. Converting Simple JSON into DataFrame

One of the most common tasks is:
- converting JSON records into tabular form

This allows us to analyze JSON data using Pandas.

---

# Example JSON Data

We will use employee records stored in JSON format.

In [ ]:
employees_json = '''
[
    {
        "name": "Ali",
        "department": "IT",
        "salary": 70000
    },
    {
        "name": "Sara",
        "department": "HR",
        "salary": 65000
    },
    {
        "name": "Ahmed",
        "department": "Finance",
        "salary": 80000
    }
]
'''

# Step 1: Convert JSON String into Python Object

We first convert JSON string into Python list/dictionary using:

```python
json.loads()
```

In [ ]:
employees_data = json.loads(employees_json)
print(employees_data)

[{'name': 'Ali', 'department': 'IT', 'salary': 70000}, {'name': 'Sara', 'department': 'HR', 'salary': 65000}, {'name': 'Ahmed', 'department': 'Finance', 'salary': 80000}]

# Understanding the Structure

After conversion:

```python
employees_data
```

becomes:
- a Python list
- containing dictionaries

Structure:

```plaintext
List
 ├── Dictionary
 ├── Dictionary
 └── Dictionary
```

This structure is perfect for DataFrame creation.

# Step 2: Convert into DataFrame

Now we convert JSON data into a Pandas DataFrame.

In [ ]:
df = pd.DataFrame(employees_data)
df

    name department  salary
0    Ali         IT   70000
1   Sara         HR   65000
2  Ahmed    Finance   80000

# What Happened Here?

Pandas automatically converted:
- dictionaries → rows
- keys → columns

---

# Result

| JSON Part | DataFrame Part |
|---|---|
| Dictionary | Row |
| Keys | Columns |
| Values | Cell values |

---

# Professional Insight

This is one of the MOST common workflows in APIs and web scraping.

# 3. Loading JSON File Directly into Pandas

Pandas can directly read JSON files using:

## `pd.read_json()`

This is similar to:
- `pd.read_csv()`
- `pd.read_excel()`

In [ ]:
import json

sample_data = [
    {"name": "Hina", "department": "HR", "salary": 72000},
    {"name": "Bilal", "department": "IT", "salary": 68000}
]

with open('employees.json', 'w') as file:
  json.dump(sample_data, file)

# Reading JSON File Using Pandas

In [ ]:
import pandas as pd

df_json = pd.read_json('employees.json')
df_json

    name department  salary
0   Hina         HR   72000
1  Bilal         IT   68000

# Why `pd.read_json()` Is Important

Benefits:
- fast loading
- direct DataFrame conversion
- useful for APIs and automation
- reduces manual processing

---

# Real-World Usage

Commonly used in:
- API responses
- cloud datasets
- structured logs
- automation pipelines

# 4. Working with Nested JSON in Pandas

Real-world JSON is usually nested.

Example:
- user details inside objects
- address inside user
- lists inside dictionaries

Nested JSON must often be flattened before analysis.

In [ ]:
nested_data = {
    "employees": [
        {
            "name": "Ali",
            "department": "IT",
            "address": {
                "city": "Lahore",
                "country": "Pakistan"
            }
        },
        {
            "name": "Sara",
            "department": "HR",
            "address": {
                "city": "Karachi",
                "country": "Pakistan"
            }
        }
    ]
}

nested_data

{'employees': [{'name': 'Ali',
   'department': 'IT',
   'address': {'city': 'Lahore', 'country': 'Pakistan'}},
  {'name': 'Sara',
   'department': 'HR',
   'address': {'city': 'Karachi', 'country': 'Pakistan'}}]}

# Understanding the Structure

```plaintext
employees
   ├── employee 1
   │      ├── name
   │      ├── department
   │      └── address
   │             ├── city
   │             └── country
   │
   └── employee 2
```

---

# Problem

Nested dictionaries are difficult to analyze directly in DataFrames.

We need to flatten them.

# 5. Flattening Nested JSON Using `json_normalize()`

Pandas provides:

## `pd.json_normalize()`

This converts nested JSON into flat table structure.

This is an extremely important professional skill.

In [ ]:
flat_df = pd.json_normalize(nested_data['employees'])
flat_df

   name department address.city address.country
0   Ali         IT       Lahore        Pakistan
1  Sara         HR      Karachi        Pakistan

# Result Explanation

Nested fields become columns like:

| Column |
|---|
| address.city |
| address.country |

---

# Why This Is Important

Flattening is heavily used in:
- API analysis
- machine learning preprocessing
- reporting systems
- data engineering pipelines

# 6. Analyzing JSON Data with Pandas

Once JSON becomes a DataFrame:
- we can analyze it like any normal dataset

Examples:
- filtering
- grouping
- statistics
- cleaning

In [ ]:
flat_df

   name department address.city address.country
0   Ali         IT       Lahore        Pakistan
1  Sara         HR      Karachi        Pakistan

In [ ]:
flat_df['department']

0    IT
1    HR
Name: department, dtype: object

# Professional Workflow

Real-world JSON workflow:

## Step 1
Receive JSON from API

## Step 2
Convert JSON into Python object

## Step 3
Convert into DataFrame

## Step 4
Flatten nested structures

## Step 5
Clean and analyze data

## Step 6
Export results

This is a standard professional workflow.

# 7. Common Beginner Mistakes

## Mistake 1: Forgetting JSON Structure

Always inspect:
- lists
- dictionaries
- nesting levels

before DataFrame conversion.

---

## Mistake 2: Trying to Analyze Raw Nested JSON

Nested JSON should usually be flattened first.

Use:

```python
pd.json_normalize()
```

---

## Mistake 3: Confusing `json.load()` and `pd.read_json()`

| Function | Purpose |
|---|---|
| `json.load()` | Convert JSON into Python objects |
| `pd.read_json()` | Load JSON directly into DataFrame |

---

## Mistake 4: Ignoring Missing Fields

Real JSON APIs may contain:
- missing keys
- null values
- inconsistent structures

# Summary

In this topic, you learned:

- converting JSON into DataFrames
- loading JSON files using Pandas
- using `pd.read_json()`
- flattening nested JSON using `pd.json_normalize()`
- analyzing structured JSON datasets

---

# Most Important Professional Insight

Modern APIs and cloud systems heavily rely on JSON.

Being able to:
- process JSON
- flatten nested structures
- convert data into DataFrames

is one of the most valuable real-world data analysis skills.