# Phase 2 — CSV Handling for Data Analysis and Freelancing

## Overview

This notebook focuses on one of the most important practical skills for data analysts and beginner freelancers: **working with CSV files**.

CSV (Comma-Separated Values) files are among the most commonly used file formats in:
- data analysis
- business reporting
- dashboards
- automation
- machine learning workflows

Most real-world datasets provided by clients, companies, and online platforms come in CSV format. Therefore, mastering CSV handling is essential for becoming a professional data analyst and starting freelance work.

---

# What We Will Cover

## 1. CSV Fundamentals
- Understanding CSV structure
- Rows, columns, and headers
- Delimiters
- CSV vs Excel files
- Why CSV is heavily used in data analysis

---

## 2. CSV Handling Using Pandas
We will deeply master:
- `pd.read_csv()`
- `df.to_csv()`

Including:
- reading datasets
- exporting processed data
- selecting columns
- handling indexes
- delimiters
- missing values
- encoding basics

This is one of the most valuable skills for beginner freelance projects.

---

## 3. Handling Dirty CSV Files
Real-world datasets are often messy and inconsistent.

We will learn how to handle:
- missing values
- wrong delimiters
- encoding issues
- inconsistent columns
- duplicate rows
- extra spaces

This is real analyst work and one of the most common freelance tasks.

---

## 4. CSV Handling Using Python `csv` Module
We will also learn practical usage of:
- `csv.reader`
- `csv.writer`
- `DictReader`

This is useful for automation scripts and lightweight CSV operations.

---

## 5. Practical CSV Projects
We will build practical mini-projects such as:
- dataset cleaning
- CSV report generation
- employee dataset analysis
- sales data processing
- CSV merger tools

These projects will help build:
- portfolio projects
- freelance confidence
- practical problem-solving skills

---

# Goal of This Phase

The main goal of this phase is to:
- become comfortable working with real-world CSV datasets
- develop practical data-cleaning skills
- build beginner freelance-ready projects
- prepare for advanced data analysis and machine learning workflows

By the end of this notebook, we will be able to handle and process CSV files professionally using Python and Pandas.

# 1. CSV Fundamentals

CSV stands for:

## Comma-Separated Values

It is one of the most commonly used file formats for storing tabular data.

CSV files are heavily used in:
- data analysis
- business reporting
- machine learning
- dashboards
- automation systems

because they are:
- simple
- lightweight
- easy to process
- supported everywhere

# 1.1 Understanding CSV Structure

A CSV file stores data in table-like form.

- each line represents a row
- values are separated using delimiters
- columns represent attributes/features

name,age,city

Ali,22,Lahore

Sara,25,Karachi

Ahmed,21,Islamabad

# Understanding the Structure

| Part | Meaning |
|---|---|
| `name, age, city` | header row |
| `Ali,22,Lahore` | data row |
| comma `,` | delimiter |

Each row contains related information about one record.

# 1.2 Rows and Columns

## Rows
Rows represent individual records.

Example:
```text
Ali,22,Lahore
```

represents one person's data.

---

## Columns
Columns represent categories/features.

Example:
- name
- age
- city

Each column stores one type of information.

# Tabular Representation

| name | age | city |
|---|---|---|
| Ali | 22 | Lahore |
| Sara | 25 | Karachi |

This table structure is why CSV files are perfect for data analysis.

# 1.3 Headers

## Concept

The first row of a CSV file usually contains column names.

This row is called:

## Header Row

name,age,city

# Why Headers are Important

Headers help:
- identify columns
- organize data
- access columns easily in pandas

Without headers:
- data becomes harder to understand
- analysis becomes confusing

# CSV Without Headers

Some CSV files may not contain headers.

Ali,22,Lahore

Sara,25,Karachi

# Professional Understanding

Most real datasets DO contain headers because:
- they improve readability
- analysis tools expect them
- easier for collaboration

# 1.4 Delimiters

## Concept

A delimiter separates values inside a row.

Most common delimiter:
```text
,
```

which is why it is called:
```text
Comma-Separated Values
```

# Common Delimiters

| Delimiter | Meaning |
|---|---|
| `,` | comma |
| `;` | semicolon |
| `\t` | tab |
| `|` | pipe |

Different datasets may use different delimiters.

# Example — Comma Delimiter

```text
Ali,22,Lahore
```

Values are separated by commas.

# Example — Semicolon Delimiter

```text
Ali;22;Lahore
```

Values are separated by semicolons.

# Why Delimiters Matter

If wrong delimiter is used:
- columns break
- data loads incorrectly
- analysis becomes invalid

This is one of the MOST common real-world CSV problems.

# 1.5 CSV vs Excel Files

CSV and Excel files both store tabular data, but they are very different internally.

# CSV Files

## Characteristics
- plain text format
- lightweight
- fast to process
- simple structure

## Extensions
```text
.csv
```

# Excel Files

## Characteristics
- richer formatting
- supports formulas
- supports multiple sheets
- heavier and more complex

## Extensions
```text
.xlsx
.xls
```

# Professional Comparison

| Feature | CSV | Excel |
|---|---|---|
| lightweight | yes | no |
| multiple sheets | no | yes |
| formatting | no | yes |
| easy processing | yes | medium |
| analyst workflows | heavily used | heavily used |

CSV is usually preferred for programming and data pipelines.

# 1.6 Why CSV is Heavily Used in Data Analysis

CSV is extremely popular because:
- simple to generate
- easy to share
- supported by almost every tool
- easy for pandas to process

# Common Sources of CSV Data

Data analysts frequently receive CSV data from:
- companies
- websites
- databases
- APIs
- dashboards
- survey systems
- business exports

# Why Analysts Love CSV Files

## 1. Easy Integration
Works with:
- Python
- Pandas
- SQL tools
- Excel
- Power BI

---

## 2. Lightweight
Fast to transfer and process.

---

## 3. Human Readable
Can be opened in text editors.

---

## 4. Perfect for Tabular Data
Matches dataframe structure directly.

# Important Professional Insight

CSV files look simple, but real-world CSV datasets can become messy because of:
- missing values
- inconsistent delimiters
- encoding issues
- broken rows

Handling these problems professionally is a major part of analyst work.

# Summary

| Concept | Meaning |
|---|---|
| CSV | Comma-Separated Values |
| rows | individual records |
| columns | attributes/features |
| headers | column names |
| delimiters | value separators |
| CSV advantage | lightweight & easy processing |

---

# Golden Rule

> CSV is the foundation of real-world data analysis workflows.

# 2. CSV Handling Using Pandas

Pandas is the MOST important library for CSV handling in data analysis.

Most beginner freelance tasks involve:
- loading CSV datasets
- cleaning data
- modifying datasets
- exporting cleaned files

The two most important functions are:

- `pd.read_csv()`
- `df.to_csv()`

Mastering these functions is one of the highest ROI skills for beginner data analysts.

# 2.1 Importing Pandas

Before working with CSV files, we import pandas.

In [ ]:
import pandas as pd

# 2.2 Creating Our First CSV File

Before learning `read_csv()`, we need a CSV file to practice on.

In [ ]:
data = """name,age,city
Ali,22,Lahore
Sara,25,Karachi
Ahmed,21,Islamabad
"""

with open('students.csv', 'w') as file:
  file.write(data)

# What This Created

A CSV file named:
```text
students.csv
```

containing:

| name | age | city |
|---|---|---|
| Ali | 22 | Lahore |
| Sara | 25 | Karachi |
| Ahmed | 21 | Islamabad |

In [ ]:
with open('students.csv', 'r') as file:
  print(file.read())

name,age,city
Ali,22,Lahore
Sara,25,Karachi
Ahmed,21,Islamabad

# 2.3 `pd.read_csv()`

## Concept

`pd.read_csv()` reads CSV files and converts them into a pandas DataFrame.

## Syntax

```python
pd.read_csv("file_name.csv")
```

In [ ]:
df = pd.read_csv('students.csv')
df

    name  age       city
0    Ali   22     Lahore
1   Sara   25    Karachi
2  Ahmed   21  Islamabad

# What is a DataFrame?

A DataFrame is a tabular data structure in pandas.

It looks similar to:
- Excel tables
- SQL tables
- CSV datasets

Most data analysis work in Python revolves around DataFrames.

# 2.4 Understanding the Output

You will see something like:

| | name | age | city |
|---|---|---|---|
| 0 | Ali | 22 | Lahore |
| 1 | Sara | 25 | Karachi |

The left-side numbers:
```python
0,1,2
```

are called:
## Indexes

# 2.5 Selecting Specific Columns While Reading

Sometimes datasets contain many unnecessary columns.

Professionals often load only required columns.

In [ ]:
df = pd.read_csv('students.csv', usecols= ['name', 'city'])
df

    name       city
0    Ali     Lahore
1   Sara    Karachi
2  Ahmed  Islamabad

# 2.5 Selecting Specific Columns While Reading

Sometimes datasets contain many unnecessary columns.

Professionals often load only required columns.

# 2.6 Handling Indexes

By default pandas creates automatic indexes.

In [ ]:
df = pd.read_csv("students.csv")

print(df.index)

RangeIndex(start=0, stop=3, step=1)

# Using a Column as Index

Sometimes datasets already contain unique identifiers.

In [ ]:
data = """id,name,age
101,Ali,22
102,Sara,25
103,Ahmed,21
"""

with open("employees.csv", "w") as file:
    file.write(data)

In [ ]:
df = pd.read_csv('employees.csv', index_col = 'id')
df

      name  age
id
101    Ali   22
102   Sara   25
103  Ahmed   21

# Why Custom Indexes are Useful

Useful for:
- unique identifiers
- database-like operations
- faster lookups
- cleaner analysis

# 2.7 Delimiters in `read_csv()`

Not all CSV files use commas.

Some datasets use:
- semicolon `;`
- tab `\t`
- pipe `|`

# Example — Semicolon Delimiter

In [ ]:
data = """name;age;city
Ali;22;Lahore
Sara;25;Karachi
"""

with open("semicolon_data.csv", "w") as file:
    file.write(data)

In [ ]:
with open("semicolon_data.csv", "r") as file:
    print(file.read())

name;age;city
Ali;22;Lahore
Sara;25;Karachi

# Problem

If we read normally:
```python
pd.read_csv()
```

pandas assumes comma delimiter.

In [ ]:
df = pd.read_csv("semicolon_data.csv")

print(df)

     name;age;city
0    Ali;22;Lahore
1  Sara;25;Karachi

# Correct Solution

Use:
```python
sep=";"
```

In [ ]:
df = pd.read_csv("semicolon_data.csv", sep = ';')
df

   name  age     city
0   Ali   22   Lahore
1  Sara   25  Karachi

# Why This is VERY Important

Wrong delimiter is one of the MOST common real-world CSV issues.

# 2.8 Skipping Rows

Some CSV files contain:
- metadata
- unnecessary top rows
- comments

We can skip them.

In [ ]:
data = """Report Generated: 2025
Company: ABC Ltd

name,age
Ali,22
Sara,25
"""

with open("report.csv", "w+") as file:
    file.write(data)
    file.seek(0)
    print(file.read())

Report Generated: 2025
Company: ABC Ltd

name,age
Ali,22
Sara,25

In [ ]:
df = pd.read_csv('report.csv', skiprows = 3)
df

   name  age
0   Ali   22
1  Sara   25

# Why This is Useful

Real company exports often contain:
- report titles
- timestamps
- notes

before actual data begins.

# 2.9 Handling Missing Values While Reading

Real datasets often contain missing values.

In [ ]:
data = """name,age,city
Ali,22,Lahore
Sara,,Karachi
Ahmed,21,
"""

with open("missing_data.csv", "w+") as file:
    file.write(data)
    file.seek(0)
    print(file.read())

name,age,city
Ali,22,Lahore
Sara,,Karachi
Ahmed,21,

In [ ]:
df = pd.read_csv("missing_data.csv")

print(df)

    name   age     city
0    Ali  22.0   Lahore
1   Sara   NaN  Karachi
2  Ahmed  21.0      NaN

# Understanding Missing Values

Pandas represents missing values as:
```python
NaN
```

which means:
```text
Not a Number
```

# Custom Missing Value Symbols

Some datasets use:
- `?`
- `N/A`
- `missing`

instead of empty cells.

In [ ]:
data = """name,age
Ali,22
Sara,?
Ahmed,N/A
Ahmed,Nan
"""

with open("custom_missing.csv", "w") as file:
    file.write(data)

In [ ]:
df = pd.read_csv(
    "custom_missing.csv",
    na_values=["?", "N/A", "Nan"]
)

print(df)

    name   age
0    Ali  22.0
1   Sara   NaN
2  Ahmed   NaN
3  Ahmed   NaN

# Why This Matters

Handling missing values correctly is a MAJOR part of analyst work.

# 2.10 Encoding Basics

Different CSV files may use different encodings.

Wrong encoding may cause:
```python
UnicodeDecodeError
```

# Most Common Encoding

The modern standard is:
```python
utf-8
```

In [ ]:
df = pd.read_csv(
    "students.csv",
    encoding="utf-8"
)

print(df)

    name  age       city
0    Ali   22     Lahore
1   Sara   25    Karachi
2  Ahmed   21  Islamabad

# Why Encoding Matters

Important for:
- Urdu text
- Arabic text
- international datasets
- special symbols

# 2.11 Exporting CSV Files — `df.to_csv()`

After cleaning or processing data, analysts often export results back to CSV.

In [ ]:
df = pd.read_csv("students.csv")

df.to_csv("output.csv")

# What Happened?

Pandas created:
```text
output.csv
```

containing dataframe data.

# 2.12 Removing Index During Export

By default pandas exports indexes too.

In [ ]:
df.to_csv('output.csv', index= False)

# Why `index=False` is Important

Without it:
- unwanted index column appears

Most professional exports use:
```python
index=False
```

# 2.13 Changing Delimiter During Export

You can export using custom delimiters.

In [ ]:
df.to_csv(
    "semicolon_output.csv",
    sep=";",
    index=False
)

# 2.14 Exporting Selected Columns

Professionals often export only required data.

# Summary

| Function | Purpose |
|---|---|
| `pd.read_csv()` | load CSV files |
| `df.to_csv()` | export CSV files |
| `usecols` | load specific columns |
| `index_col` | set custom index |
| `sep` | define delimiter |
| `skiprows` | skip unwanted rows |
| `na_values` | define missing values |
| `encoding` | handle text encoding |
| `index=False` | remove indexes during export |

---

# Golden Rule

> Most beginner data analyst freelance work revolves around reading, cleaning, and exporting CSV files using pandas.

In [ ]:
data = """
wow, wew, wewe
ok, man, hj

id,name,age,city
1,Ali,22,?
2,Sara,,Karachi
3,Ahmed,21,Nil
"""
with open("students.csv", "w") as file:
    file.write(data)

In [ ]:
df=pd.read_csv('students.csv',skiprows=3,index_col='id',sep=',',na_values=['?','Nil'],encoding='utf-8')
df

     name   age     city
id
1     Ali  22.0      NaN
2    Sara   NaN  Karachi
3   Ahmed  21.0      NaN

# 3. Handling Dirty CSV Files

Real-world datasets are rarely clean.

Most datasets contain problems such as:
- missing values
- broken formatting
- duplicate rows
- inconsistent columns
- encoding issues

A major part of a data analyst's job is:
```text
Cleaning messy data
```

This is one of the MOST common freelance tasks.

# 3.1 Missing Values

## Concept

Missing values occur when some data is absent.

Example:
- missing age
- missing city
- incomplete records

In [ ]:
import pandas as pd

data = """name,age,city
Ali,22,Lahore
Sara,,Karachi
Ahmed,21,
"""

with open("missing_values.csv", "w") as file:
    file.write(data)

In [ ]:
df = pd.read_csv("missing_values.csv")

print(df)

    name   age     city
0    Ali  22.0   Lahore
1   Sara   NaN  Karachi
2  Ahmed  21.0      NaN

# Understanding Missing Values

Pandas represents missing values as:
```python
NaN
```

Meaning:
```text
Not a Number
```

Missing values are EXTREMELY common in real datasets.

# Detecting Missing Values

We can detect missing values using:
```python
isnull()
```

In [ ]:
print(df.isnull())

    name    age   city
0  False  False  False
1  False   True  False
2  False  False   True

In [ ]:
df.isna()

    name    age   city
0  False  False  False
1  False   True  False
2  False  False   True

# Counting Missing Values

Professionals often count missing values quickly.

In [ ]:
print(df.isnull().sum())

name    0
age     1
city    1
dtype: int64

In [ ]:
df.isna().sum()

name    0
age     1
city    1
dtype: int64

# Removing Rows with Missing Values

Sometimes incomplete rows are removed.

In [ ]:
cleaned = df.dropna()
cleaned

  name   age    city
0  Ali  22.0  Lahore

# Important Understanding

```python
dropna()
```

removes rows containing missing values.

# Filling Missing Values

Sometimes removing data is not a good idea.

We can fill missing values instead.

In [ ]:
filled_df = df.fillna("Unknown")

print(filled_df)

    name      age     city
0    Ali     22.0   Lahore
1   Sara  Unknown  Karachi
2  Ahmed     21.0  Unknown

# Real Analyst Work

Handling missing values is one of the MOST important analyst skills.

# 3.2 Wrong Delimiters

Many datasets use wrong or unexpected delimiters.

In [ ]:
data = """name;age;city
Ali;22;Lahore
Sara;25;Karachi
"""

with open("wrong_delimiter.csv", "w") as file:
    file.write(data)

In [ ]:
df = pd.read_csv("wrong_delimiter.csv")

print(df)

     name;age;city
0    Ali;22;Lahore
1  Sara;25;Karachi

# Problem

Pandas assumed:
```python
sep=","
```

But file uses:
```text
;
```

So data loaded incorrectly.

# Correct Solution

In [ ]:
df = pd.read_csv(
    "wrong_delimiter.csv",
    sep=";"
)

print(df)

   name  age     city
0   Ali   22   Lahore
1  Sara   25  Karachi

# Why This is Important

Wrong delimiters are VERY common in:
- exported reports
- European datasets
- business systems

# 3.3 Encoding Issues

Different files may use different text encodings.

Wrong encoding may cause:
```python
UnicodeDecodeError
```

In [ ]:
df = pd.read_csv(
    "missing_values.csv",
    encoding="utf-8"
)

print(df)

    name   age     city
0    Ali  22.0   Lahore
1   Sara   NaN  Karachi
2  Ahmed  21.0      NaN

# Why Encoding Problems Happen

Encoding issues commonly occur with:
- Urdu text
- Arabic text
- special characters
- old systems

# Professional Tip

If UTF-8 fails, analysts often try:
```python
latin-1
```

or:
```python
cp1252
```

# 3.4 Inconsistent Columns

Some datasets contain rows with different numbers of columns.

This breaks CSV structure.

In [ ]:
data = """name,age,city
Ali,22,Lahore
Sara,25
Ahmed,21,Islamabad,Extra
"""

with open("inconsistent.csv", "w") as file:
    file.write(data)

In [ ]:
#df = pd.read_csv("inconsistent.csv")
#Raise Error

# What Happened?

Some rows contain:
- fewer columns
- extra columns

Pandas cannot properly parse inconsistent structures.

# Professional Understanding

This is VERY common in:
- manually edited CSVs
- corrupted exports
- broken data pipelines

# Skipping Bad Rows

Professionals sometimes skip broken rows temporarily.

In [ ]:
df = pd.read_csv(
    "inconsistent.csv",
    on_bad_lines="skip"
)

print(df)

   name  age    city
0   Ali   22  Lahore
1  Sara   25     NaN

# Important Note

This should be used carefully because:
- bad data gets ignored
- information may be lost

# 3.5 Duplicate Rows

Duplicate data is extremely common.

In [ ]:
data = """name,age
Ali,22
Sara,25
Ali,22
"""

with open("duplicates.csv", "w") as file:
    file.write(data)

In [ ]:
df = pd.read_csv("duplicates.csv")

print(df)

   name  age
0   Ali   22
1  Sara   25
2   Ali   22

# Detecting Duplicate Rows

In [ ]:
print(df.duplicated())

0    False
1    False
2     True
dtype: bool

# Removing Duplicate Rows

In [ ]:
clean_df = df.drop_duplicates()

print(clean_df)

   name  age
0   Ali   22
1  Sara   25

# Why Duplicate Handling Matters

Duplicate rows can:
- distort analysis
- inflate statistics
- create incorrect reports

# 3.6 Extra Spaces

Real datasets often contain unnecessary spaces.

In [ ]:
data = """name,city
 Ali , Lahore
Sara , Karachi
"""

with open("spaces.csv", "w") as file:
    file.write(data)

In [ ]:
df = pd.read_csv("spaces.csv")

print(df)

    name      city
0   Ali     Lahore
1  Sara    Karachi

# Problem

Extra spaces create inconsistent values.

Example:
```text
Ali
```

and:
```text
 Ali
```

are treated differently.

# Removing Extra Spaces

In [ ]:
df["name"] = df["name"].str.strip()
df["city"] = df["city"].str.strip()

print(df)

   name     city
0   Ali   Lahore
1  Sara  Karachi

# Why Cleaning Spaces is Important

Extra spaces can:
- break filtering
- create duplicate categories
- damage analysis accuracy

# Exporting Cleaned Dataset

In [ ]:
clean_df.to_csv(
    "cleaned_dataset.csv",
    index=False
)

# Important Professional Advice

Real-world data cleaning is usually:
```text
80% cleaning
20% analysis
```

Many beginner analysts underestimate how important cleaning skills are.

# Summary

| Problem | Solution |
|---|---|
| missing values | `dropna()`, `fillna()` |
| wrong delimiters | `sep=` |
| encoding issues | `encoding=` |
| inconsistent columns | `on_bad_lines="skip"` |
| duplicate rows | `drop_duplicates()` |
| extra spaces | `str.strip()` |

---

# Golden Rule

> Real datasets are messy. A professional analyst knows how to clean data before analyzing it.

# 4. CSV Handling Using `csv` Module

Along with Pandas, Python also provides a built-in module called:

## `csv` module

This module is used for basic CSV operations without needing external libraries.

It is useful for:
- simple CSV processing
- automation scripts
- lightweight data tasks
- understanding how CSV works internally

# 4.1 Importing csv Module

Since it is built-in, no installation is required.

In [ ]:
import csv

# 4.2 Creating a Sample CSV File

We will create a file to practice reading and writing.

In [ ]:
data = """name,age,city
Ali,22,Lahore
Sara,25,Karachi
Ahmed,21,Islamabad
"""

with open("people.csv", "w") as file:
    file.write(data)

# 4.3 `csv.reader`

## Concept

`csv.reader` reads CSV files row by row.

Each row is returned as a list.

In [ ]:
with open("people.csv", "r") as file:
  reader = csv.reader(file)
  for row in reader:
    print(row)

['name', 'age', 'city']
['Ali', '22', 'Lahore']
['Sara', '25', 'Karachi']
['Ahmed', '21', 'Islamabad']

# Understanding Output

Each row becomes a list:

```python
['name', 'age', 'city']
['Ali', '22', 'Lahore']
['Sara', '25', 'Karachi']
```

So:
- each row = list of values
- everything is treated as text

# Why csv.reader is Useful

It is useful when:
- you want low-level control
- you are processing files manually
- you are building simple scripts

# 4.4 Skipping Header Row

Sometimes we don’t want the header row.

In [ ]:
with open('people.csv', 'r') as file:
  reader = csv.reader(file)

  next(reader) #skip row

  for row in reader:
    print(row)

['Ali', '22', 'Lahore']
['Sara', '25', 'Karachi']
['Ahmed', '21', 'Islamabad']

# 4.5 `csv.writer`

## Concept

`csv.writer` is used to write data into CSV files.

In [ ]:
data = [
    ["name", "age", "city"],
    ["Ali", 22, "Lahore"],
    ["Sara", 25, "Karachi"],
    ["Ahmed", 21, "Islamabad"]
]

print(data)

[['name', 'age', 'city'], ['Ali', 22, 'Lahore'], ['Sara', 25, 'Karachi'], ['Ahmed', 21, 'Islamabad']]

In [ ]:
with open("output.csv", "w+", newline="") as file:
    writer = csv.writer(file)

    writer.writerows(data)
    file.seek(0)

    print(file.read())

name,age,city
Ali,22,Lahore
Sara,25,Karachi
Ahmed,21,Islamabad

# Understanding writerows()

```python
writer.writerows(data)
```

writes multiple rows at once.

# Single Row Writing

If we want to write one row:

In [ ]:
with open('output2.csv', 'w+', newline="") as file:
  writer = csv.writer(file)

  writer.writerow(['name','age','city'])
  writer.writerow(['Ali',22,'Lahore'])
  writer.writerow(['Sara',25,'Karachi'])
  file.seek(0)
  print(file.read())

name,age,city
Ali,22,Lahore
Sara,25,Karachi

# Why newline="" is Important

Without:
```python
newline=""
```

extra blank lines may appear in CSV files.

This is a common beginner mistake.

# 4.6 `csv.DictReader`

## Concept

`DictReader` reads CSV files as dictionaries instead of lists.

In [ ]:
with open("people.csv", "r") as file:
    reader = csv.DictReader(file)

    for row in reader:
        print(row)

{'name': 'Ali', 'age': '22', 'city': 'Lahore'}
{'name': 'Sara', 'age': '25', 'city': 'Karachi'}
{'name': 'Ahmed', 'age': '21', 'city': 'Islamabad'}

# Understanding Output

Each row becomes:

```python
{'name': 'Ali', 'age': '22', 'city': 'Lahore'}
```

So:
- keys = column names
- values = row data

# Why DictReader is Powerful

Advantages:
- more readable
- easier data access
- avoids index confusion

Example:
```python
row["name"]
```

instead of:
```python
row[0]
```

# 4.7 Practical Use Case

Example: printing only names

In [ ]:
with open("people.csv", "r") as file:
    reader = csv.DictReader(file)

    for row in reader:
        print(row['name'])

Ali
Sara
Ahmed

# 4.8 csv vs Pandas (Important Insight)

| Feature | csv module | Pandas |
|---|---|---|
| ease of use | low | high |
| power | basic | advanced |
| data analysis | limited | full |
| freelancing use | rare | very common |

---

# Conclusion

For freelancing:
- Pandas is PRIMARY
- csv module is SUPPORTING tool

# 4.9 When to Use csv Module

Use it when:
- building small scripts
- working with simple files
- avoiding heavy libraries
- learning how CSV works internally

# Summary

| Function | Purpose |
|---|---|
| csv.reader | read CSV as lists |
| csv.writer | write CSV files |
| DictReader | read CSV as dictionaries |

---

# Golden Rule

> For real data analysis and freelancing, Pandas is essential. The csv module is mainly for basic and low-level operations.